### ISSUE TITLE
Holos Controller

### ISSUE THREAD

**Issue by jeffmccune** [holos-run/holos#129]
Add a `holos controller` sub-command which starts Machine Room and connects to the holos server backend infrastructure.  Note this is an epic, add tasks as they're identified.

> [!NOTE]
> Refer to last year's Machine Room Spike: https://github.com/openinfrastructure/holos/issues/269

# Overview

The overall process a `holos controller` goes through is:

 1. Connect to a Choria Provisioning system to obtain NATS user jwt creds.
 2. Choria Provisioning system returns credentials good for the SaaS NATS cluster.
 3. Holos Controller disconnects from the provisioner and connects to the SaaS websocket using the provisioned credentials.

> [!IMPORTANT]
> Given this flow, we setup a Choria broker and provisioner to bootstrap `holos controller`.  We also setup NATS which the controller connects two once provisioned.

# Tasks

- [x] #130
- [x] #132
- [x] Provisioner wss endpoint for the agent with mTLS DestinationRule
- [x] #133
- [ ] Create Agent API - Called by end user
- [ ] Provision Agent API - Called by Provisioner Helper
- [ ] Integrate Provisioner Helper with Provision Agent API
- [x] #142
- [x] #141
- [ ] Add `holos` to the provisioner container as a sidecar container
- [ ] NATS wss endpoint for the agent
- [ ] Agent Registration
- [ ] Agent pulls down platform oci image full of CUE code
- [ ] Agent renders one or more components
- [ ] Agent serves up rendered output for ArgoCD
- [ ] ArgoCD reconciles rendered output from the Agent

# Notes

> [!WARNING]
> When managing a DestinationRule to perform mTLS to the Choria Broker and to NATS, take care to set the `subjectAltnames` correctly, otherwise the connection will fail TLS validation at the ingress proxy.

Button Up
- [ ] Internal mTLS for NATS
- [ ] nats-box persistent volume
- [ ] Operator JWT in an ExternalSecret.  See [Config Includes](https://github.com/nats-io/k8s/tree/main/helm/charts/nats#nats-config-includes)
